import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ProtectedRoute from "@/context/ProtectedRoute";
import StoreProvider from "@/store/StoreProvider";
import { AlertMessage } from "@/components/AlertMessage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <StoreProvider>

            <ProtectedRoute>
              {children}
            </ProtectedRoute>
            <AlertMessage />
          </StoreProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
